name: KMM Bridge Publish Release
on:
  workflow_dispatch:

jobs:
  call-kmmbridge-publish:
    uses: touchlab/KMMBridgeGithubWorkflow/.github/workflows/faktorybuildbranches.yml@179644fc5ffb8719c5d8db00e627389d0bfb4ef1 # v0.3
